
package lavadero;


public class Vista extends javax.swing.JFrame {

    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1LavadoEsp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1TipoVehiculo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1Funcionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2CantidadLavado = new javax.swing.JTextField();
        jLabel5LavadoEsp = new javax.swing.JLabel();
        jTextField2LavadoEsp = new javax.swing.JTextField();
        jLabel5DesinfeccionBas = new javax.swing.JLabel();
        jTextField3DesinfeccionBas = new javax.swing.JTextField();
        jLabel5DesinfeccionAvanz = new javax.swing.JLabel();
        jTextField3DesinfeccionAvanz = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3Combo1 = new javax.swing.JTextField();
        jTextField3Combo2 = new javax.swing.JTextField();
        jTextField3Combo3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3TotalLavadoBas = new javax.swing.JTextField();
        jTextField3TotalLavadoEspecial = new javax.swing.JTextField();
        jTextField3TotalDesinfeccionBasica = new javax.swing.JTextField();
        jTextField3TotalDesinfeccionAvanzada = new javax.swing.JTextField();
        jTextField3TotalCombos = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField1TotalFuncionario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1LavadoEsp.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1LavadoEsp.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel1.setText("LAVADERO DE AUTOS");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel2.setText("Tipo Vehículo (Automóvil o Camioneta)");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel3.setText("Empleado");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel4.setText("Lavado Básico (día)");

        jLabel5LavadoEsp.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel5LavadoEsp.setText("Lavado Especial(día)");

        jLabel5DesinfeccionBas.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel5DesinfeccionBas.setText("Desinfección Básica(día)");

        jLabel5DesinfeccionAvanz.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel5DesinfeccionAvanz.setText("Desinfección Avanzada(día)");

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel5.setText("Combo 1");

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel6.setText("Combo 2");

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel7.setText("Combo 3");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel8.setText("Producción por Servicio");

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel9.setText("Total Lavados Básicos");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel10.setText("Total Lavado Especial");

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel11.setText("Total Desinfección Básica");

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel12.setText("Total Desinfección Avanzada");

        jLabel13.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel13.setText("Total Combos");

        jTextField3TotalLavadoBas.setEditable(false);

        jTextField3TotalLavadoEspecial.setEditable(false);

        jTextField3TotalDesinfeccionBasica.setEditable(false);

        jTextField3TotalDesinfeccionAvanzada.setEditable(false);

        jTextField3TotalCombos.setEditable(false);

        jButtonCalcular.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCalcular.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jButtonCalcular.setForeground(new java.awt.Color(102, 255, 102));
        jButtonCalcular.setText("Calcular");

        jLabel14.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel14.setText("Total Funcionario");

        jTextField1TotalFuncionario.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel15.setText("Tarifa = $ Pesos Colombianos");

        javax.swing.GroupLayout jPanel1LavadoEspLayout = new javax.swing.GroupLayout(jPanel1LavadoEsp);
        jPanel1LavadoEsp.setLayout(jPanel1LavadoEspLayout);
        jPanel1LavadoEspLayout.setHorizontalGroup(
            jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3DesinfeccionAvanz, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jTextField3DesinfeccionBas)
                            .addComponent(jTextField2LavadoEsp)
                            .addComponent(jTextField2CantidadLavado))
                        .addGap(97, 97, 97))
                    .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3Combo1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                    .addComponent(jTextField3Combo2)
                                    .addComponent(jTextField3Combo3)))
                            .addComponent(jLabel5DesinfeccionAvanz)
                            .addComponent(jLabel5DesinfeccionBas)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5LavadoEsp)
                            .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel13)))
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jTextField3TotalDesinfeccionBasica, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField1TotalFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField3TotalCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3TotalDesinfeccionAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE))))
                    .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3TotalLavadoBas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3TotalLavadoEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1LavadoEspLayout.createSequentialGroup()
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonCalcular, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1TipoVehiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(jTextField1Funcionario, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(39, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1LavadoEspLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1LavadoEspLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1LavadoEspLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(226, 226, 226))))
        );
        jPanel1LavadoEspLayout.setVerticalGroup(
            jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1TipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2CantidadLavado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5LavadoEsp)
                                    .addComponent(jTextField2LavadoEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5DesinfeccionBas)
                                    .addComponent(jTextField3DesinfeccionBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5DesinfeccionAvanz)
                                    .addComponent(jTextField3DesinfeccionAvanz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField3Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField3Combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField3Combo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1LavadoEspLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField3TotalLavadoBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField3TotalLavadoEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3TotalDesinfeccionBasica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField3TotalDesinfeccionAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField3TotalCombos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1LavadoEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField1TotalFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCalcular)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1LavadoEsp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1LavadoEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel5DesinfeccionAvanz;
    public javax.swing.JLabel jLabel5DesinfeccionBas;
    public javax.swing.JLabel jLabel5LavadoEsp;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1LavadoEsp;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField jTextField1Funcionario;
    public javax.swing.JTextField jTextField1TipoVehiculo;
    public javax.swing.JTextField jTextField1TotalFuncionario;
    public javax.swing.JTextField jTextField2CantidadLavado;
    public javax.swing.JTextField jTextField2LavadoEsp;
    public javax.swing.JTextField jTextField3Combo1;
    public javax.swing.JTextField jTextField3Combo2;
    public javax.swing.JTextField jTextField3Combo3;
    public javax.swing.JTextField jTextField3DesinfeccionAvanz;
    public javax.swing.JTextField jTextField3DesinfeccionBas;
    public javax.swing.JTextField jTextField3TotalCombos;
    public javax.swing.JTextField jTextField3TotalDesinfeccionAvanzada;
    public javax.swing.JTextField jTextField3TotalDesinfeccionBasica;
    public javax.swing.JTextField jTextField3TotalLavadoBas;
    public javax.swing.JTextField jTextField3TotalLavadoEspecial;
    // End of variables declaration//GEN-END:variables
}
